### ISSUE TITLE
消息模块

### ISSUE THREAD

**Issue by zhicheng-ning** [X-Engineer/x-tiktok#12]

**Comment by zhicheng-ning** [comment]
已完成消息发送和聊天记录功能
遇到的问题：

- 获取聊天记录时显示网络异常，使用 PostMan 测试时，后端可以返回出内容

![image](https://user-images.githubusercontent.com/39022409/216778664-554d0374-f8a6-4d03-93f9-701999fd48fa.png)

**Comment by zhicheng-ning** [comment]
目前主要疑惑点在于：
关于 /douyin/message/chat/ - 聊天记录接口的说明，抖音项目说明文档以及 Apifox 接口文档关于返回内容结构不一致

**Comment by zhicheng-ning** [comment]
Apifox：
![image](https://user-images.githubusercontent.com/39022409/216778847-265ff88e-0c76-44cb-970f-139dbc74df7e.png)

抖音项目说明文档：
![image](https://user-images.githubusercontent.com/39022409/216778863-20fe8319-ba45-4418-8717-389dae21167c.png)

**Comment by zhicheng-ning** [comment]
使用 apktool 对抖声 apk 反编译之后，可以确定其消息内容格式是项目说明文档中所介绍的

![image](https://user-images.githubusercontent.com/39022409/216800231-fc7fc15b-afa5-43c5-a27e-1f0c7fa57ab2.png)

![image](https://user-images.githubusercontent.com/39022409/216800250-df5d3e8c-3927-4408-b9d3-668d12131f0e.png)

**Comment by coder-zc** [comment]
tql

**Comment by zhicheng-ning** [comment]
当前 app 端 bug，猜测原因，轮询获取最新聊天记录，但是前端并未将旧的聊天记录覆盖：

![tiktok-chatmessage](https://user-images.githubusercontent.com/39022409/217574824-77fd61d6-2bc9-4779-8267-d2639c016af4.gif)

**Comment by zhicheng-ning** [comment]
修复聊天记录叠加的问题


<img src="https://user-images.githubusercontent.com/39022409/219394059-9d4dc16d-7eb9-4555-90fe-05efc4d249f0.gif" width="40%">

**Comment by zhicheng-ning** [comment]
官方又提供了新的 app 安装包，附加了 pre_msg_time 字段，不用自己维护了，，

![image](https://user-images.githubusercontent.com/39022409/219675178-48c08fca-7e8b-4297-baa0-c8c877e13390.png)
