### ISSUE TITLE
[feature]关注服务提供函数

### ISSUE THREAD

**Issue by coder-zc** [X-Engineer/x-tiktok#19]
1. 根据用户id查询粉丝数：即该用户被多少人关注
2. 根据用户id查询关注数：即该用户关注了多少人

**Comment by coder-zc** [comment]
@dongzhengyu816 
@Xuuuuuuuuuuuu 
拜托两位好兄弟了！

**Comment by zhicheng-ning** [comment]
我看这两个方法，在 followDao 是实现了，但是还没在 followService 暴露出来，此外，还需要提供一个判断当前登录用户是否关注了目标用户的方法

**Comment by Xuuuuuuuuuuuu** [comment]
> 我看这两个方法，在 followDao 是实现了，但是还没在 followService 暴露出来，此外，还需要提供一个判断当前登录用户是否关注了目标用户的方法

这三个方法：1. 根据用户id查询粉丝数：即该用户被多少人关注；2.根据用户id查询关注数：即该用户关注了多少人；3.判断当前登录用户是否关注了目标用户的方法。是需要在service里单独提供嘛，我马上加上。

**Comment by Xuuuuuuuuuuuu** [comment]
> 1. 根据用户id查询粉丝数：即该用户被多少人关注
> 2. 根据用户id查询关注数：即该用户关注了多少人

1. GetFollowingCnt(userId int64) (int64, error)
2. GetFollowerCnt(userId int64) (int64, error)
3. CheckIsFollowing(userId int64, targetId int64) (bool, error)
还没提交诶嘿写好鉴权再交

**Comment by zhicheng-ning** [comment]
> 这三个方法：1. 根据用户id查询粉丝数：即该用户被多少人关注；2.根据用户id查询关注数：即该用户关注了多少人；3.判断当前登录用户是否关注了目标用户的方法。是需要在service里单独提供嘛

是的~
