### ISSUE TITLE
[bug] 评论时会显示用户名，再次进入评论列表则不显示用户名

### ISSUE THREAD

**Issue by zhicheng-ning** [X-Engineer/x-tiktok#49]
@coder-zc 测试效果如下

|  评论时   | 评论后  |
|  ----  | ----  |
| <img src="https://user-images.githubusercontent.com/39022409/219939568-65b4cd0c-0db4-4b85-96ba-789ae4b5d198.png" width="100%">   | <img src="https://user-images.githubusercontent.com/39022409/219939588-37c4132e-d53a-4808-9995-3a259e94a5c0.png" width="100%"> |

**Comment by zhicheng-ning** [comment]
问题应该出在：这部分判断条件应该有问题吧，err == nil 时，导致 comment 没有设置 user 

https://github.com/X-Engineer/x-tiktok/blob/4bdaeff74d0be16faabbaa0d3b4fa99506532d07/service/commentServiceImpl.go#L91-L101

**Comment by coder-zc** [comment]
是的，这里写Bug了。已修正！
