### ISSUE TITLE
[bug] 评论内容应该按发表时间降序显示~

### ISSUE THREAD

**Issue by zhicheng-ning** [X-Engineer/x-tiktok#59]
评论内容应该按时间降序显示~

<img src="https://user-images.githubusercontent.com/39022409/220564963-a582f8dc-ed54-4a37-a362-941b980095bf.png" width="60%">

**Comment by zhicheng-ning** [comment]
评论删除好像正常了

**Comment by coder-zc** [comment]
收到

**Comment by coder-zc** [comment]
https://github.com/X-Engineer/x-tiktok/pull/60
已修复
